# Generated by Django 3.0.5 on 2020-04-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='deliveryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickupName', models.CharField(max_length=30)),
                ('pickupStreetAddress', models.CharField(max_length=100)),
                ('pickupCity', models.CharField(max_length=20)),
                ('pickupState', models.CharField(max_length=2)),
                ('pickupZipcode', models.IntegerField()),
                ('dropoffName', models.CharField(max_length=30)),
                ('dropoffStreetAddress', models.CharField(max_length=100)),
                ('dropoffCity', models.CharField(max_length=20)),
                ('dropoffState', models.CharField(max_length=2)),
                ('dropoffZipcode', models.IntegerField()),
                ('item', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='posts', to='DeliverApp.Category')),
            ],
        ),
    ]
