# Generated by Django 3.0.5 on 2020-04-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliverApp', '0002_deliveryrequest_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='author',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='categories',
        ),
    ]
