# Generated by Django 3.0.5 on 2020-04-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliverApp', '0003_auto_20200426_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='dropoffZipcode',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='pickupZipcode',
            field=models.CharField(max_length=5),
        ),
    ]
