# Generated by Django 3.0.5 on 2020-04-26 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DeliverApp', '0004_auto_20200426_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='author',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
