# Generated by Django 3.0.5 on 2020-04-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliverApp', '0005_auto_20200426_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='author',
        ),
    ]
