# Generated by Django 3.0.5 on 2020-04-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliverApp', '0006_remove_deliveryrequest_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='jobAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
